const { chromium } = require("playwright");
const db = require("./db");
const fs = require("fs");
const path = require("path");

(async () => {
    const browser = await chromium.launch({ headless: true });
    const page = await browser.newPage();

    try {
        console.log("🚀 Starting Sync Process...");

        // 0. Backup existing data
        const backupDir = path.join(__dirname, "backups");
        if (!fs.existsSync(backupDir)) fs.mkdirSync(backupDir, { recursive: true });

        try {
            const [citiesRows] = await db.query("SELECT * FROM maharashtra_cities");
            const [stationsRows] = await db.query("SELECT * FROM maharashtra_police_stations");

            if (citiesRows.length > 0) {
                const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
                const backupPath = path.join(backupDir, `backup_${timestamp}.json`);
                const readmePath = path.join(backupDir, `backup_${timestamp}_README.md`);

                fs.writeFileSync(backupPath, JSON.stringify({ cities: citiesRows, stations: stationsRows }, null, 2));

                const readmeContent = `# Backup Summary - ${new Date().toLocaleString()}
                
## Metadata
- **Date**: ${new Date().toDateString()}
- **Time**: ${new Date().toTimeString()}
- **File**: \`backup_${timestamp}.json\`

## Statistics
- **Total Cities**: ${citiesRows.length}
- **Total Police Stations**: ${stationsRows.length}

---
*This backup was automatically generated by the sync script.*
`;
                fs.writeFileSync(readmePath, readmeContent);

                console.log(`📦 Backup created: ${backupPath}`);
                console.log(`📝 README created: ${readmePath}`);
            }
        } catch (err) {
            console.log("ℹ️ No existing data to backup or tables don't exist yet.");
        }

        // 1. Create Tables

        await db.query(`
            CREATE TABLE IF NOT EXISTS maharashtra_cities (
                id INT AUTO_INCREMENT PRIMARY KEY,
                city_id VARCHAR(50) NOT NULL UNIQUE,
                city_name VARCHAR(255) NOT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
            )
        `);

        await db.query(`
            CREATE TABLE IF NOT EXISTS maharashtra_police_stations (
                id INT AUTO_INCREMENT PRIMARY KEY,
                station_id VARCHAR(50) NOT NULL UNIQUE,
                station_name VARCHAR(255) NOT NULL,
                city_id VARCHAR(50) NOT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                INDEX (city_id)
            )
        `);

        console.log("✅ Tables ensured.");

        // 2. Fetch Cities
        console.log("🔍 Fetching cities...");
        await page.goto("https://citizen.mahapolice.gov.in/citizen/mh/PublishedFIRs.aspx", { waitUntil: "load" });
        await page.reload({ waitUntil: "load" });

        await page.waitForFunction(() => {
            const ddl = document.querySelector("#ContentPlaceHolder1_ddlDistrict");
            return ddl && ddl.options.length > 1;
        }, { timeout: 30000 });

        const cities = await page.evaluate(() => {
            return Array.from(document.querySelectorAll("#ContentPlaceHolder1_ddlDistrict option"))
                .filter(o => o.value && o.value !== "0")
                .map(o => ({
                    id: o.value,
                    name: o.textContent.trim()
                }));
        });

        console.log(`📍 Found ${cities.length} cities.`);

        // 3. Insert/Update Cities and Fetch Stations
        for (const city of cities) {
            console.log(`🌆 Processing City: ${city.name} (${city.id})...`);

            await db.query(`
                INSERT INTO maharashtra_cities (city_id, city_name)
                VALUES (?, ?)
                ON DUPLICATE KEY UPDATE city_name = VALUES(city_name)
            `, [city.id, city.name]);

            // Select City to load stations
            await page.selectOption("#ContentPlaceHolder1_ddlDistrict", city.id);

            try {
                await page.waitForFunction(() => {
                    const ps = document.querySelector("#ContentPlaceHolder1_ddlPoliceStation");
                    return ps && ps.options.length > 1;
                }, { timeout: 10000 });

                const stations = await page.evaluate(() => {
                    return Array.from(document.querySelectorAll("#ContentPlaceHolder1_ddlPoliceStation option"))
                        .filter(o => o.value && o.value !== "0" && o.value !== "Select")
                        .map(o => ({
                            id: o.value,
                            name: o.textContent.trim()
                        }));
                });

                console.log(`   🚉 Found ${stations.length} stations.`);

                for (const station of stations) {
                    await db.query(`
                        INSERT INTO maharashtra_police_stations (station_id, station_name, city_id)
                        VALUES (?, ?, ?)
                        ON DUPLICATE KEY UPDATE station_name = VALUES(station_name), city_id = VALUES(city_id)
                    `, [station.id, station.name, city.id]);
                }
            } catch (err) {
                console.log(`   ⚠️ Could not load stations for ${city.name}: ${err.message}`);
            }
        }

        console.log("🎉 Sync completed successfully!");

    } catch (err) {
        console.error("❌ Sync Error:", err);
    } finally {
        await browser.close();
        process.exit();
    }
})();
